module.exports = [
  {
    "firstName": "Demo",
    "lastName": "Demo",
    "email": "demo@demo.com",
    "password": "123456",
    "mobileNumber": "9258632148",
    "taxiNumber": "TX 481",
    "taxiType": "Sedan5",
    "wheelChair": "YES",
    "pets": "YES",
    "parcel": "YES",
    "parcelType": "SMALL",
    "food": "YES",
  },
  {
    "firstName": "Emilia",
    "lastName": "Epps",
    "email": "emilia@demo.com",
    "password": "123456",
    "mobileNumber": "9258632856",
    "taxiNumber": "TX 482",
    "taxiType": "Sedan5",
    "wheelChair": "YES",
    "pets": "YES",
    "parcel": "YES",
    "parcelType": "SMALL",
    "food": "YES",
  },
  {
    "firstName": "Perry",
    "lastName": "Kingsley",
    "email": "perry@demo.com",
    "password": "123456",
    "mobileNumber": "9258632179",
    "taxiNumber": "TX 483",
    "taxiType": "Sedan5",
    "wheelChair": "YES",
    "pets": "YES",
    "parcel": "YES",
    "parcelType": "SMALL",
    "food": "YES",
  },
  {
    "firstName": "Joseph",
    "lastName": "Garrison",
    "email": "joseph@demo.com",
    "password": "123456",
    "mobileNumber": "9258635689",
    "taxiNumber": "TX 484",
    "taxiType": "Sedan5",
    "wheelChair": "YES",
    "pets": "YES",
    "parcel": "YES",
    "parcelType": "SMALL",
    "food": "YES",
  },
  {
    "firstName": "Ella",
    "lastName": "Morrissey",
    "email": "morrissey@demo.com",
    "password": "123456",
    "mobileNumber": "9258678452",
    "taxiNumber": "TX 485",
    "taxiType": "Sedan5",
    "wheelChair": "YES",
    "pets": "YES",
    "parcel": "YES",
    "parcelType": "SMALL",
    "food": "YES",
  },
  {
    "firstName": "Elizabeth",
    "lastName": "Forshee",
    "email": "elizabeth@demo.com",
    "password": "123456",
    "mobileNumber": "9258678458",
    "taxiNumber": "TX 486",
    "taxiType": "Sedan5",
    "wheelChair": "YES",
    "pets": "YES",
    "parcel": "YES",
    "parcelType": "SMALL",
    "food": "YES",
  },
  {
    "firstName": "Douglas",
    "lastName": "Arce",
    "email": "douglas@demo.com",
    "password": "123456",
    "mobileNumber": "9258924548",
    "taxiNumber": "TX 487",
    "taxiType": "Sedan5",
    "wheelChair": "YES",
    "pets": "YES",
    "parcel": "YES",
    "parcelType": "SMALL",
    "food": "YES",
  },
  {
    "firstName": "Sara",
    "lastName": "Nixon",
    "email": "sara@demo.com",
    "password": "123456",
    "mobileNumber": "9258256268",
    "taxiNumber": "TX 488",
    "taxiType": "Sedan5",
    "wheelChair": "YES",
    "pets": "YES",
    "parcel": "YES",
    "parcelType": "SMALL",
    "food": "YES",
  },
  {
    "firstName": "Edward",
    "lastName": "Jett",
    "email": "edward@demo.com",
    "password": "123456",
    "mobileNumber": "9292451648",
    "taxiNumber": "TX 489",
    "taxiType": "Sedan5",
    "wheelChair": "YES",
    "pets": "YES",
    "parcel": "YES",
    "parcelType": "SMALL",
    "food": "YES",
  },
  {
    "firstName": "Marilyn",
    "lastName": "Bradley",
    "email": "marilyn@demo.com",
    "password": "123456",
    "mobileNumber": "9253128488",
    "taxiNumber": "TX 490",
    "taxiType": "Sedan5",
    "wheelChair": "YES",
    "pets": "YES",
    "parcel": "YES",
    "parcelType": "SMALL",
    "food": "YES",
  },
  {
    "firstName": "Herman",
    "lastName": "Thompson",
    "email": "herman@demo.com",
    "password": "123456",
    "mobileNumber": "7845924516",
    "taxiNumber": "TX 491",
    "taxiType": "Sedan5",
    "wheelChair": "YES",
    "pets": "YES",
    "parcel": "YES",
    "parcelType": "SMALL",
    "food": "YES",
  },
  {
    "firstName": "Darrin",
    "lastName": "Neely",
    "email": "darrin@demo.com",
    "password": "123456",
    "mobileNumber": "9123456788",
    "taxiNumber": "TX 492",
    "taxiType": "Sedan5",
    "wheelChair": "YES",
    "pets": "YES",
    "parcel": "YES",
    "parcelType": "SMALL",
    "food": "YES",
  },
  {
    "firstName": "Ralph",
    "lastName": "Vaughn",
    "email": "ralph@demo.com",
    "password": "123456",
    "mobileNumber": "9258944312",
    "taxiNumber": "TX 493",
    "taxiType": "Sedan5",
    "wheelChair": "YES",
    "pets": "YES",
    "parcel": "YES",
    "parcelType": "SMALL",
    "food": "YES",
  },
  {
    "firstName": "Arturo",
    "lastName": "Gibson",
    "email": "arturo@demo.com",
    "password": "123456",
    "mobileNumber": "9867892848",
    "taxiNumber": "TX 494",
    "taxiType": "Sedan5",
    "wheelChair": "YES",
    "pets": "YES",
    "parcel": "YES",
    "parcelType": "SMALL",
    "food": "YES",
  },
  {
    "firstName": "Kevin",
    "lastName": "Delacruz",
    "email": "kevin@demo.com",
    "password": "123456",
    "mobileNumber": "9282569656",
    "taxiNumber": "TX 495",
    "taxiType": "Sedan5",
    "wheelChair": "YES",
    "pets": "YES",
    "parcel": "YES",
    "parcelType": "SMALL",
    "food": "YES",
  },
]